"""add_role_name_to_role_user_mappings

Revision ID: 6812c0ffa6b9
Revises: 336885acc43a
Create Date: 2026-02-12 12:25:20.160129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6812c0ffa6b9'
down_revision: Union[str, Sequence[str], None] = '336885acc43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_user_mappings', sa.Column('role_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_user_mappings', 'role_name')
    # ### end Alembic commands ###
